force-app/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Partner_Membership__c/Program_Partner_Membership__c.object-meta.xml
<CustomObject>
    <label>Program Partner Membership</label>
    <nameField>
        <displayFormat>ID-{0000}</displayFormat>
        <label>Program Partner Membership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Partner Memberships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Program_Partner_Membership__c/fields/Bitly_Link_to_Post_Coaching_Survey__c.field-meta.xml
<CustomField>
    <fullName>Bitly_Link_to_Post_Coaching_Survey__c</fullName>
    <description>The Pardot redirect link with encoded program id and cohort id url parameters that is provided to members of a cohort when it is time for them to take the post-coaching survey. Available in the portal.</description>
    <inlineHelpText>Paste the result from Pardot redirect into this field.</inlineHelpText>
    <label>Bitly Link to Post-Coaching Survey</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program_Partner_Membership__c/fields/Bitly_Link_To_Resili__c.field-meta.xml
<CustomField>
    <fullName>Bitly_Link_To_Resili__c</fullName>
    <description>The bitly link that we provide to entrepreneurs to signup for RESILI.  Uses the aeo_state field in this formula and then turn into a bitly link using Pardot redirect. Redirects to here: https://resili.aeoworks.org/business-health-assessment/?aeo_state=btoa(aeo_state)</description>
    <inlineHelpText>Enter the bitly link from the Pardot redirect here.</inlineHelpText>
    <label>Bitly Link To Resili</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Program_Partner_Membership__c/fields/Cohort__c.field-meta.xml
<CustomField>
    <fullName>Cohort__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cohort</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Programs</relationshipLabel>
    <relationshipName>Program_Partner_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Program_Partner_Membership__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Cohorts</relationshipLabel>
    <relationshipName>Program_Partner_Memberships</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/GettingStartedController.cls
public class GettingStartedController {


  @AuraEnabled
  /**
   * @description Return the following fields for the running user who is logged in to the portal for the 
   * given program.
   * - cohortId - the Cohort ID (Account ID)
   * - userId - the User ID
   * - bitlyResili - the Bitly Link to RESILI 
   * - bitlyPostCoach - the Bitly Link to Post-Coaching Survey
   * 
   * @param  programName the name of the program for the portal (e.g., Wells Fargo)
   * @return             A json string like {"cohortId": "xxxxx", "userId":"yyyyyy", ...}
   */
  public static String serverGetUserCohortAndLinks(String programName) {
    String userId;
    String cohortId;

    List<User> UserRec = [
      SELECT contact.account.name, contact.accountId
      FROM user
      WHERE contact.accountId != NULL AND id = :UserInfo.getUserId()
    ];
    cohortId = UserRec[0].contact.accountId;
    userId = UserInfo.getUserId();
    Map<String, String> returnMap = new Map<String, String>();
    returnMap.put('cohortId', cohortId);
    returnMap.put('userId', userId);
    List<Program__c> programList = [
      SELECT Id FROM Program__c WHERE Name = :programName
    ];
    Id programId = null;
    if (programList.size() > 0) {
      programId = programList[0].Id;
    }
    List<Program_Partner_Membership__c> cohortProgramList = [
      SELECT Bitly_Link_to_Post_Coaching_Survey__c, Bitly_Link_To_Resili__c
      FROM Program_Partner_Membership__c
      WHERE Program__c = :programId AND Cohort__c = :cohortId
    ];
    if (cohortProgramList.size() > 0) {
      Program_Partner_Membership__c cohortProgram = cohortProgramList[0];
      returnMap.put('bitlyResili', cohortProgram.Bitly_Link_To_Resili__c);
      returnMap.put('bitlyPostCoach', cohortProgram.Bitly_Link_to_Post_Coaching_Survey__c);
    }
    return JSON.serialize(returnMap);

  }
  
}